name = "SardMoreira"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["SardMoreira"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "master"

[[require]]
name = "checkdecls"
scope = "PatrickMassot"
rev = "master"

[[require]]
name = "«doc-gen4»"
scope = "leanprover"
rev = "main"

[[lean_lib]]
name = "SardMoreira"
