name = "SardMoreira"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["SardMoreira"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "d62eab0cc36ea522904895389c301cf8d844fd69"

# [[require]]
# name = "checkdecls"
# git = "https://github.com/urkud/checkdecls.git"
# rev = "YK-fix-superscript"

# [[require]]
# name = "«doc-gen4»"
# git = "https://github.com/leanprover/doc-gen4"
# rev = "main"

[[lean_lib]]
name = "SardMoreira"
